### ISSUE TITLE
microfw tear_down and HAVE-MANGLE seems not to work for me

### ISSUE THREAD

**Issue by weratyr** [Svedrin/microfw#5]
systemd[1]: Starting MicroFW...
microfw[589]: iptables v1.8.6 (nf_tables): Chain 'MFWINPUT' does not exist
microfw[589]: Try `iptables -h' or 'iptables --help' for more information.
systemd[1]: microfw.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: microfw.service: Failed with result 'exit-code'.
systemd[1]: Failed to start MicroFW.

This line seems to break it: 
https://github.com/Svedrin/microfw/blob/master/src/microfw.sh#L75

**Comment by Svedrin** [comment]
I think the whole [`tear_down` function](https://github.com/Svedrin/microfw/blob/6c6594ee9005e07f39240dc2de284e5c14a0bb63/src/microfw.sh#L56) should run without `set -e`. Lemme prepare a PR.
