### ISSUE TITLE
Power loss or crash breaks tear_down/startup implementation

### ISSUE THREAD

**Issue by weratyr** [Svedrin/microfw#6]
If the host have accidentally  a power loss or a system crash, the `ExecStop=/usr/local/sbin/microfw tear_down` will not be called. This leads to a startup error if you boot up your machine again. 
The reason for that is the `ExecStartPre=/usr/local/sbin/microfw tear_down` will fail due to the fact there is actually nothing to do for `tear_down` but the `state.txt` still exists.

**Comment by Svedrin** [comment]
https://github.com/Svedrin/microfw/pull/4#pullrequestreview-719964469

> @weratyr I'm wondering if we should move the state file to `/dev/shm`, which is stored in RAM, so that it's gone after a reboot. This might improve stability of the whole thing. Wdyt?
